#ifndef YAI_GRAPH_EDGE_KIND_SCHEMA_H
#define YAI_GRAPH_EDGE_KIND_SCHEMA_H

#include "yai/base/error.h"

typedef enum yai_graph_schema_edge_kind {
    YAI_GRAPH_SCHEMA_EDGE_BELONGS_TO_CASE = 0,
    YAI_GRAPH_SCHEMA_EDGE_SUBJECT_PARTICIPATES_IN_CASE = 1,
    YAI_GRAPH_SCHEMA_EDGE_ATTEMPT_TARGETS_SUBJECT = 2,
    YAI_GRAPH_SCHEMA_EDGE_DECISION_CONTROLS_ATTEMPT = 3,
    YAI_GRAPH_SCHEMA_EDGE_REVIEW_REQUEST_FOR_ATTEMPT = 4,
    YAI_GRAPH_SCHEMA_EDGE_REVIEW_DECISION_RESOLVES_REQUEST = 5,
    YAI_GRAPH_SCHEMA_EDGE_CONTROL_PENDING_BLOCKS_ATTEMPT = 6,
    YAI_GRAPH_SCHEMA_EDGE_REVIEW_RESOLUTION_PRODUCES_RECEIPT = 7,
    YAI_GRAPH_SCHEMA_EDGE_DISPATCH_ROUTES_DECISION = 8,
    YAI_GRAPH_SCHEMA_EDGE_CARRIER_REALIZES_DISPATCH = 9,
    YAI_GRAPH_SCHEMA_EDGE_RECEIPT_RECORDS_EFFECT = 10,
    YAI_GRAPH_SCHEMA_EDGE_OBSERVATION_CHECKS_EFFECT = 11,
    YAI_GRAPH_SCHEMA_EDGE_DIVERGENCE_DESCRIBES_MISMATCH = 12,
    YAI_GRAPH_SCHEMA_EDGE_POLICY_CONSTRAINS_SUBJECT = 13,
    YAI_GRAPH_SCHEMA_EDGE_POLICY_CONSTRAINS_OPERATION = 14,
    YAI_GRAPH_SCHEMA_EDGE_PROJECTION_EXPOSES_RECORD = 15,
    YAI_GRAPH_SCHEMA_EDGE_MODEL_OUTPUT_PRODUCES_INTERPRETATION = 16,
    YAI_GRAPH_SCHEMA_EDGE_MEMORY_DERIVED_FROM_RECEIPT = 17,
    YAI_GRAPH_SCHEMA_EDGE_RECORD_MATERIALIZES_NODE = 18,
    YAI_GRAPH_SCHEMA_EDGE_DERIVED_FROM = 19,
    YAI_GRAPH_SCHEMA_EDGE_SUPPORTS = 20,
    YAI_GRAPH_SCHEMA_EDGE_CONTRADICTS = 21,
    YAI_GRAPH_SCHEMA_EDGE_UNKNOWN = 22
} yai_graph_schema_edge_kind_t;

const char *yai_graph_schema_edge_kind_string(yai_graph_schema_edge_kind_t kind);
yai_status_t yai_graph_schema_edge_kind_from_string(const char *value,
                                                    yai_graph_schema_edge_kind_t *kind);

#endif
