#ifndef YAI_H
#define YAI_H

#define YAI_CORE_VERSION "0.0.0-newcore"

#include "yai/base/error.h"
#include "yai/base/id.h"
#include "yai/case/case_context.h"
#include "yai/case/case_ref.h"
#include "yai/case/case_session.h"
#include "yai/case/case_world.h"
#include "yai/control/decision_basis.h"
#include "yai/control/decision.h"
#include "yai/control/failure_mode.h"
#include "yai/control/gate.h"
#include "yai/control/obligation.h"
#include "yai/control/policy_rule.h"
#include "yai/control/receipt_requirement.h"
#include "yai/daemon/daemon_loop.h"
#include "yai/daemon/daemon_status.h"
#include "yai/daemon/ipc.h"
#include "yai/daemon/ipc_message.h"
#include "yai/effect/carrier.h"
#include "yai/effect/effect_hash.h"
#include "yai/effect/filesystem_carrier.h"
#include "yai/effect/receipt.h"
#include "yai/graph/edge.h"
#include "yai/graph/graph.h"
#include "yai/graph/reconstruct.h"
#include "yai/index/query.h"
#include "yai/index/query_filter.h"
#include "yai/index/query_result.h"
#include "yai/memory/memory_candidate.h"
#include "yai/memory/memory_kind.h"
#include "yai/memory/memory_scope.h"
#include "yai/op/attempt.h"
#include "yai/projection/freshness.h"
#include "yai/projection/projection.h"
#include "yai/projection/projection_kind.h"
#include "yai/projection/projection_request.h"
#include "yai/projection/projection_result.h"
#include "yai/projection/redaction.h"
#include "yai/reconcile/divergence.h"
#include "yai/reconcile/reconcile.h"
#include "yai/reconcile/recovery.h"
#include "yai/store/journal.h"
#include "yai/store/journal_file.h"
#include "yai/store/record.h"
#include "yai/store/record_codec.h"
#include "yai/store/rust_engine_backend.h"
#include "yai/subject/subject_binding.h"
#include "yai/subject/subject_ref.h"
#include "yai/subject/subject_state.h"

#endif
